aeravat/aeravat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
        path('', (include('studentprofile.urls'))),
                path('', (include('roadmap.urls'))),
                path('', (include('AIinterview_app.urls'))),
                path('', (include('myron.urls'))),
    path('social-auth/', include('social_django.urls', namespace='social')),


]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aeravat/myron/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns=[
    path('companies/',companies,name='companies'),
    path('aboutamazon/',aboutamazon,name='aboutamazon'),
    path('amazonaptitude/',amazonaptitude,name='amazonaptitude'),

    # URL for displaying quiz detail
    path('quiz1/<int:quiz_id>/', quiz_detail, name='quiz_detail'),    
    path('quiz_list/', quiz_list, name='quiz_list'),
    path('save_response/', save_response, name='save_response'),

     # Your existing quiz URLs
    path('quiz_list/', quiz_list, name='quiz_list'),
    path('save_response/', save_response, name='save_response'),

]

aeravat/studentprofile/models.py
from django.db import models

class StudentProfile(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    linkedin_profile = models.URLField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    skills = models.CharField(max_length=1000, null=True, blank=True)
    projects = models.CharField(max_length=1000, null=True, blank=True)
    desired_role = models.CharField(max_length=100, null=True, blank=True)
    preferred_industry = models.CharField(max_length=100, null=True, blank=True)
    technology_interests = models.CharField(max_length=255, null=True, blank=True)
    current_year = models.IntegerField(null=True, blank=True)  # New field
    placement_year = models.IntegerField(null=True, blank=True)  # New field

    def __str__(self):
        return self.name


# models.py

from django.db import models
from django.contrib.auth.models import User

class Quiz(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE,null=True, blank=True)
    text = models.CharField(max_length=255,null=True, blank=True)
    topic = models.CharField(max_length=100, null=True, blank=True)  # Add a topic field

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE,null=True, blank=True)
    choice_text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

class UserAnswer(models.Model):
    student_profile = models.ForeignKey(StudentProfile, on_delete=models.CASCADE,null=True, blank=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE,null=True, blank=True)
    selected_choice = models.ForeignKey(Choice, on_delete=models.CASCADE,null=True, blank=True)

    def is_correct(self):
        return self.selected_choice.is_correct

aeravat/templates/student/jobs.html
{% extends 'base.html' %}
{% block content %}
<div id="content-page" class="content-page">
    <div class="container-fluid">
        <div class="row">
            <div class="iq-card-body">
                <div class="iq-card">
     
                


    {% if jobs %}

    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Job Listings</h4>
        </div>
        <div class="table-responsive">
            <table class="table align-middle table-striped">
                <thead>
                    <tr>
                        <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Title</th>
                        <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Company Name</th>
                        <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Description</th>
                        <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Apply</th>
                    </tr>
                </thead>
                <tbody>
                    {% for job in jobs %}
                    <tr>
                        <td>
                            <div class="d-flex align-items-center">
                                <div class="avatar avatar-sm me-3">
                                    {% if job.thumbnail %}
                                    <img src="{{ job.thumbnail }}" alt="{{ job.company_name }}" style="width: 100px;">
                                    {% else %}
                                    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_0HvCCSj9gEOrWNZkwtHu4J1LffvlO667BER_RP7bqUaAI4qdWFxsmwVXkpugBCYhb6I&usqp=CAU" alt="Default Thumbnail" style="max-width: 100px;">
                                    {% endif %}
                                </div>
                                <div>
                                    <h6 class="mb-0 text-xs">{{ job.title }}</h6>
                                    <p class="text-xs text-secondary mb-0">{{ job.company_name }}</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <p class="text-xs mb-0">{{ job.company_name }}</p>
                        </td>
                        <td>
                            <p class="text-xs text-secondary mb-0">{{ job.description|truncatechars:100 }}</p>
                        </td>
                        <td class="text-center">
                            {% if job.related_links %}
                                {% for link in job.related_links %}
                                    <a class="btn btn-primary btn-sm" href="{{ link.link }}" target="_blank">Apply</a>
                                {% endfor %}
                            {% else %}
                                <span class="text-secondary text-xs">No links available</span>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
    {% endif %}

</div>
{% endblock %}

aeravat/templates/student/mentor.html
{% extends 'base1.html' %}
{% block content %}
{% load static %}
<script src="{% static 'assets1/js/plugins/swiper-bundle.min.js' %}"></script>
<div class="position-relative overflow-hidden">
    <div class="swiper mySwiper mt-4 mb-2">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <div>
            <div class="card card-background shadow-none border-radius-xl card-background-after-none align-items-start mb-0">
              <div class="full-background bg-cover" style="background-image: url('https://th.bing.com/th/id/OIG2.MX0q748yC93SfKwevma3?w=1024&h=1024&rs=1&pid=ImgDetMain')"></div>
              <div class="card-body text-start px-3 py-0 w-100">
                <div class="row mt-12">
                  <div class="col-sm-3 mt-auto">
                    <h4 class="text-white font-weight-bolder no_toc">Aachal Jain</h4>
                    <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">SDE-1</p>
                    <h5 class="text-white font-weight-bolder no_toc">Google</h5>
                  </div>
                  <div class="col-sm-3 ms-auto mt-auto">
                    <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">Front End Dev</p>
                    <a href="https://aryan.digitalsamba.com/demo-room" target="_blank" class="btn btn-primary mt-3">Connect</a>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="swiper-slide">
          <div class="card card-background shadow-none border-radius-xl card-background-after-none align-items-start mb-0">
            <div class="full-background bg-cover" style="background-image: url('https://th.bing.com/th/id/OIG1.hd4MlArVFWHi4nWD8yl6?pid=ImgGn')"></div>
            <div class="card-body text-start px-3 py-0 w-100">
              <div class="row mt-12">
                <div class="col-sm-3 mt-auto">
                  <h4 class="text-white font-weight-bolder no_toc">Satwik Joshi</h4>
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">SDE-1</p>
                  <h5 class="text-white font-weight-bolder no_toc">Google</h5>
                </div>
                <div class="col-sm-3 ms-auto mt-auto">
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">FullStack</p>
                  <a href="https://aryan.digitalsamba.com/demo-room" target="_blank" class="btn btn-primary mt-3">Connect</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="swiper-slide">
          <div class="card card-background shadow-none border-radius-xl card-background-after-none align-items-start mb-0">
            <div class="full-background bg-cover" style="background-image: url('https://th.bing.com/th/id/OIG2.IA9hoBabF40Ssh66RqUS?pid=ImgGn')"></div>
            <div class="card-body text-start px-3 py-0 w-100">
              <div class="row mt-12">
                <div class="col-sm-3 mt-auto">
                  <h4 class="text-white font-weight-bolder no_toc">Bhavesh Joshi</h4>
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">SWE-3</p>
                  <h5 class="text-white font-weight-bolder no_toc">Google</h5>
                </div>
                <div class="col-sm-3 ms-auto mt-auto">
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">ReactDev</p>
                  <a href="https://aryan.digitalsamba.com/demo-room" target="_blank" class="btn btn-primary mt-3">Connect</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="swiper-slide">
          <div class="card card-background shadow-none border-radius-xl card-background-after-none align-items-start mb-0">
            <div class="full-background bg-cover" style="background-image: url('https://th.bing.com/th/id/OIG4.K4p5q4TTRKi8oI1HaMxM?w=1024&h=1024&rs=1&pid=ImgDetMain')"></div>
            <div class="card-body text-start px-3 py-0 w-100">
              <div class="row mt-12">
                <div class="col-sm-3 mt-auto">
                  <h4 class="text-white font-weight-bolder no_toc">Tenali Rama</h4>
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">Intern</p>
                  <h5 class="text-white font-weight-bolder no_toc">Ex Google</h5>
                </div>
                <div class="col-sm-3 ms-auto mt-auto">
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">Frontend</p>
                  <a href="https://aryan.digitalsamba.com/demo-room" target="_blank" class="btn btn-primary mt-3">Connect</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="swiper-slide">
          <div class="card card-background shadow-none border-radius-xl card-background-after-none align-items-start mb-0">
            <div class="full-background bg-cover" style="background-image: url('https://th.bing.com/th/id/OIG4.rdBmRWG9435fO9WYs3n8?pid=ImgGn')"></div>
            <div class="card-body text-start px-3 py-0 w-100">
              <div class="row mt-12">
                <div class="col-sm-3 mt-auto">
                  <h4 class="text-white font-weight-bolder no_toc">Mustafa Ali</h4>
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">Tech Lead</p>
                  <h5 class="text-white font-weight-bolder no_toc">Google</h5>
                </div>
                <div class="col-sm-3 ms-auto mt-auto">
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">Full Stack</p>
                  <a href="https://aryan.digitalsamba.com/demo-room" target="_blank" class="btn btn-primary mt-3">Connect</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="swiper-slide">
          <div class="card card-background shadow-none border-radius-xl card-background-after-none align-items-start mb-0">
            <div class="full-background bg-cover" style="background-image: url('https://th.bing.com/th/id/OIG2.4RzkZJrzbLDoMFBEFwz6?pid=ImgGn')"></div>
            <div class="card-body text-start px-3 py-0 w-100">
              <div class="row mt-12">
                <div class="col-sm-3 mt-auto">
                  <h4 class="text-white font-weight-bolder no_toc">Award Anshuman</h4>
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">CTO</p>
                  <h5 class="text-white font-weight-bolder no_toc">Ex Google,AWS</h5>
                </div>
                <div class="col-sm-3 ms-auto mt-auto">
                  <p class="text-white opacity-6 text-xs font-weight-bolder mb-0">Fullstack</p>
                  <a href="https://aryan.digitalsamba.com/demo-room" target="_blank" class="btn btn-primary mt-3">Connect</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
  
  </div>
<script>

  var swiper = new Swiper(".mySwiper", {
    effect: "cards",
    grabCursor: true,
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
  });
  
  </script>
<!-- Include Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
document.addEventListener('DOMContentLoaded', function () {
var strengthsData = {{ strengths_chart_data|safe }};
var improvementsData = {{ improvements_chart_data|safe }};

new Chart(document.getElementById('strengthChart'), {
type: 'doughnut',
data: strengthsData,
options: { responsive: true, maintainAspectRatio: false }
});

new Chart(document.getElementById('improvementChart'), {
type: 'doughnut',
data: improvementsData,
options: { responsive: true, maintainAspectRatio: false }
});
});
</script>
{% endblock %}

aeravat/templates/student/quiz_results.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container-fluid py-4">
    <div class="row">
      <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
        <div class="card">
          <div class="card-header p-3 pt-2">
            <div class="icon icon-lg icon-shape bg-gradient-dark shadow-dark text-center border-radius-xl mt-n4 position-absolute">
              <i class="material-icons opacity-10">weekend</i>
            </div>
            <div class="text-end pt-1">
              <p class="text-sm mb-0 text-capitalize">Ranking</p>
              <h4 class="mb-0">2822</h4>
            </div>
          </div>
          <hr class="dark horizontal my-0">
          <div class="card-footer p-3">
            <p class="mb-0"><span class="text-success text-sm font-weight-bolder">+55% </span>than mates</p>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
        <div class="card">
          <div class="card-header p-3 pt-2">
            <div class="icon icon-lg icon-shape bg-gradient-primary shadow-primary text-center border-radius-xl mt-n4 position-absolute">
              <i class="material-icons opacity-10">person</i>
            </div>
            <div class="text-end pt-1">
              <p class="text-sm mb-0 text-capitalize">Score</p>
              <h4 class="mb-0">{{ score }}</h4>
            </div>
          </div>
          <hr class="dark horizontal my-0">
          <div class="card-footer p-3">
            <p class="mb-0"><span class="text-success text-sm font-weight-bolder">+3% </span>than mates</p>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
        <div class="card">
          <div class="card-header p-3 pt-2">
            <div class="icon icon-lg icon-shape bg-gradient-success shadow-success text-center border-radius-xl mt-n4 position-absolute">
              <i class="material-icons opacity-10">person</i>
            </div>
            <div class="text-end pt-1">
              <p class="text-sm mb-0 text-capitalize">Level</p>
              <h4 class="mb-0">{{ proficiency_level }}</h4>
            </div>
          </div>
          <hr class="dark horizontal my-0">
          <div class="card-footer p-3">
            <p class="mb-0"><span class="text-danger text-sm font-weight-bolder">-2%</span> than yesterday</p>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-sm-6">
        <div class="card">
          <div class="card-header p-3 pt-2">
            <div class="icon icon-lg icon-shape bg-gradient-info shadow-info text-center border-radius-xl mt-n4 position-absolute">
              <i class="material-icons opacity-10">weekend</i>
            </div>
            <div class="text-end pt-1">
              <p class="text-sm mb-0 text-capitalize">Strength</p>
              {% for strength in strengths %}
              <h4 class="mb-0">{{ strength }}</h4>
              {% endfor %}

            </div>
          </div>
          <hr class="dark horizontal my-0">
          <div class="card-footer p-3">
            <p class="mb-0"><span class="text-success text-sm font-weight-bolder">+5% </span>than yesterday</p>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <div class="row mt-4">
      <div class="col-lg-6 col-md-8 mt-4 mb-4">
          <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
              <div class="card mb-6">
                  <div class="card-body p-3">
                      <h5>Areas of Strength</h5>
                      <div class="chart">
                          <canvas id="strengthsChart" class="chart-canvas"></canvas>
                      </div>
                  </div>
              </div>
          </div>        
      </div>
      <div class="col-lg-6 col-md-8 mt-4 mb-4">
          <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
              <div class="card mb-6">
                  <div class="card-body p-3">
                      <h5>Areas for Improvement</h5>
                      <div class="chart">
                          <canvas id="improvementsChart" class="chart-canvas"></canvas>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  
  
          <script>
            document.addEventListener('DOMContentLoaded', function() {
                var strengthsLabels = {{ strengths | safe }};
                var improvementsLabels = {{ improvements | safe }};
            
                // A simple function to generate a distinct background color array
                function generateBackgroundColors(count) {
                    const colors = ['#4caf50', '#2196f3', '#ffeb3b', '#ff9800', '#f44336'];
                    let bgColors = [];
                    for (let i = 0; i < count; i++) {
                        bgColors.push(colors[i % colors.length]);
                    }
                    return bgColors;
                }
            
                var strengthsChartData = {
                    labels: strengthsLabels,
                    datasets: [{
                        data: strengthsLabels.map(() => 1), // Assuming equal value for simplicity; you might want to adjust
                        backgroundColor: generateBackgroundColors(strengthsLabels.length),
                        hoverOffset: 4
                    }]
                };
            
                var improvementsChartData = {
                    labels: improvementsLabels,
                    datasets: [{
                        data: improvementsLabels.map(() => 1), // Assuming equal value for simplicity; adjust as necessary
                        backgroundColor: generateBackgroundColors(improvementsLabels.length),
                        hoverOffset: 4
                    }]
                };
            
                var ctxStrengths = document.getElementById('strengthsChart').getContext('2d');
                var strengthsChart = new Chart(ctxStrengths, {
                    type: 'doughnut',
                    data: strengthsChartData,
                });
            
                var ctxImprovements = document.getElementById('improvementsChart').getContext('2d');
                var improvementsChart = new Chart(ctxImprovements, {
                    type: 'doughnut',
                    data: improvementsChartData,
                });
            });
            </script>
            
            
{% endblock %}

aeravat/templates/student/skill_assessment.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">

        <div class="row">
            <!-- Left Column for Test Cases and Questions -->
            <div class="col-md-6">
                <div>
                    <h1>{{ quiz.title }}</h1>
                    <form method="POST">
                        {% csrf_token %}
                        {% for question in questions %}
                            <div>
                                <p>{{ question.text }}</p>
                                {% for choice in question.choice_set.all %}
                                    <input type="radio" name="{{ question.id }}" value="{{ choice.id }}">
                                    <label>{{ choice.choice_text }}</label><br>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <input type="submit" value="Submit">
                    </form>
                </div>
            </div>
<iframe id="compilerFrame"
    frameBorder="0"
    height="600px"
    src="https://onecompiler.com/embed/"
    width="100%">
</iframe>
<!-- Include modal structure within the skill assessment HTML template -->


<!-- JavaScript to handle the modal and load quiz results -->


{% endblock %}

aeravat/templates/student/student_courses.html
{% extends 'base.html' %}
{% block content %}

<div id="content-page" class="content-page">
  <div class="container-fluid">
      <div class="row">
          <div class="iq-card-body">
              <div class="iq-card">
        <h1>Courses</h1>
        <div class="iq-card-body">

        <form id="time-filter-form">
          
            <div class="form-group">
              <label>Filter by Time:</label><br>
              <input type="checkbox" id="time-0-10" name="time" value="0-10">
              <label for="time-0-10">0-10 mins</label><br>
              <input type="checkbox" id="time-10-30" name="time" value="10-30">
              <label for="time-10-30">10-30 mins</label><br>
              <input type="checkbox" id="time-30-60" name="time" value="30-60">
              <label for="time-30-60">30-60 mins</label><br>
              <input type="checkbox" id="time-60+" name="time" value="60+">
              <label for="time-60+">More than 60 mins</label>
            </div>
          </form>
          
          <div class="row" id="course-cards">
            {% for course in courses %}
                <div class="col-sm-4 course-card" data-length="{{ course.length }}">
                   <div class="card iq-mb-3">
                    {% if course.link %}
                    {% with video_id=course.link|cut:"https://www.youtube.com/watch?v=" %}
                    <iframe src="https://www.youtube.com/embed/{{ video_id }}?autoplay=0&mute=1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen height="280"></iframe>
                    {% endwith %}
                    {% endif %}                      
                    <div class="card-body">
                         <h4 class="card-title">{{ course.title }}</h4>
                         <p class="card-text">Views: {{ course.views }}</p>
                         <a href="{{ course.link }}" class="btn dark-icon btn-primary" target="_blank">Watch</a>
                        </div>
                   </div>
                </div>
            {% empty %}
            <p>No courses found.</p>
            {% endfor %}
          </div>
      </div>
  </div>
<script>
 document.querySelectorAll('#time-filter-form input[type="checkbox"]').forEach(function(checkbox) {
  checkbox.addEventListener('change', function() {
    filterCourses();
  });
});

function filterCourses() {
  var checkboxes = document.querySelectorAll('#time-filter-form input[type="checkbox"]:checked');
  var filters = Array.from(checkboxes).map(function(checkbox) { return checkbox.value; });
  var courseCards = document.querySelectorAll('.course-card');

  courseCards.forEach(function(card) {
    var length = parseInt(card.getAttribute('data-length'), 10);
    var display = false;

    if (filters.length === 0) {
      display = true;
    } else {
      for (let filter of filters) {
        if (filter === '0-10' && length <= 10) {
          display = true;
          break;
        } else if (filter === '10-30' && length > 10 && length <= 30) {
          display = true;
          break;
        } else if (filter === '30-60' && length > 30 && length <= 60) {
          display = true;
          break;
        } else if (filter === '60+' && length > 60) {
          display = true;
          break;
        }
      }
    }

    card.style.display = display ? 'block' : 'none';
  });
}

// Initially call filterCourses to apply the filter on page load if any checkbox is already checked.
filterCourses();
</script>
{% endblock %}